name: Bug Report
description: Report a bug
title: "[BUG] "
labels: ["bug"]
body:
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: A brief description of the issue.
      placeholder: "A bug happened!"
    validations:
      required: true
  - type: textarea
    id: how-to-reproduce
    attributes:
      label: How can we reproduce it?
      placeholder: "1. Run: ...\n2. See error [describe what went wrong] ..."
    validations:
      required: true
  - type: textarea
    id: expected-behaviour
    attributes:
      label: What did you expect to happen?
      description: A brief description of what you expected.
