name: Feature Request
description: Suggest an idea for a new feature
title: "[FEATURE] "
labels: ["feature"]
body:
  - type: textarea
    id: problem
    attributes:
      label: What problem are you trying to solve?
    validations:
      required: true
  - type: textarea
    id: improvement
    attributes:
      label: What would you like to see?
      description: A brief description of the feature or improvement.
    validations:
      required: true
  - type: textarea
    id: details
    attributes:
      label: Any additional context?
      description: Add any other details or examples here.
