basePath: /
definitions:
  auth.AccessTokenResponseModel:
    properties:
      access_token:
        type: string
    type: object
  auth.LoginRequestModel:
    properties:
      email:
        type: string
      password:
        type: string
    type: object
  auth.SignupRequestModel:
    properties:
      dob:
        type: string
      email:
        type: string
      first_name:
        type: string
      gender:
        type: string
      last_name:
        type: string
      password:
        type: string
      phone_number:
        type: string
    type: object
  response.Error:
    properties:
      message:
        type: string
      status:
        type: integer
    type: object
  response.InvalidField:
    properties:
      error:
        type: string
      field:
        type: string
    type: object
  response.ValidationError:
    properties:
      invalid_fields:
        items:
          $ref: '#/definitions/response.InvalidField'
        type: array
      message:
        type: string
      status:
        type: integer
    type: object
host: localhost:8080
info:
  contact: {}
  description: Documentation for the gdsi API
  title: Gdsi API
  version: 1.0.0
paths:
  /v1/auth/signup:
    post:
      consumes:
      - application/json
      description: Signup a new account
      parameters:
      - description: Request body
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/auth.SignupRequestModel'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/auth.AccessTokenResponseModel'
        "400":
          description: Bad request
          schema:
            $ref: '#/definitions/response.ValidationError'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/response.Error'
      summary: Signup
      tags:
      - auth
  /v1/auth/tokens/access:
    post:
      consumes:
      - application/json
      description: Login and get a new access token
      parameters:
      - description: Request body
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/auth.LoginRequestModel'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/auth.AccessTokenResponseModel'
        "400":
          description: Bad request
          schema:
            $ref: '#/definitions/response.ValidationError'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/response.Error'
      summary: Login
      tags:
      - auth
  /v1/auth/tokens/refresh:
    get:
      consumes:
      - application/json
      description: Get a refreshed access token
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/auth.AccessTokenResponseModel'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/response.Error'
      summary: Refresh token
      tags:
      - auth
swagger: "2.0"
